[default]
extend-ignore-re = [
  # Custom ignore regex patterns: https://github.com/crate-ci/typos/blob/master/docs/reference.md#example-configurations
  ".*(?:#|--|//|/*).*(?:typos):\\s?ignore[^\\n]*\\n",
]

[files]
extend-exclude = ["vendor"]
