[licenses]
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "MIT",
  "Unicode-3.0",
  "Zlib",
  "Apache-2.0 WITH LLVM-exception",
  "ISC",
  "MPL-2.0",
  "CC0-1.0",
  "bzip2-1.0.6",
  "CDLA-Permissive-2.0",
]
