// @generated from `crates/cheers/src/validation` by the `validation_table_is_up_to_date`
// test. Regenerate it with `UPDATE_VALIDATION_TABLE=1 cargo test -p cheers-ast`.

use super::{Element, Globals, Module};
use crate::generate::ElementKind::{Normal, Void, Xml};

const GLOBAL_ATTRIBUTES: Globals = Globals {
    attributes: &["access_key", "autocapitalize", "autofocus", "class", "contenteditable", "dir", "draggable", "enterkeyhint", "hidden", "id", "inert", "inputmode", "is", "itemid", "itemprop", "itemref", "itemscope", "itemtype", "lang", "nonce", "popover", "role", "slot", "spellcheck", "style", "tabindex", "title", "translate"],
    namespaces: &["aria", "data"],
};

const SVG_GLOBAL_ATTRIBUTES: Globals = Globals {
    attributes: &["alignment_baseline", "autofocus", "baseline_shift", "class", "clip", "clip_path", "clip_rule", "color", "color_interpolation", "color_interpolation_filters", "cursor", "d", "direction", "display", "dominant_baseline", "enable_background", "fill", "fill_opacity", "fill_rule", "filter", "flood_color", "flood_opacity", "font_family", "font_size", "font_size_adjust", "font_stretch", "font_style", "font_variant", "font_weight", "glyph_orientation_horizontal", "glyph_orientation_vertical", "id", "image_rendering", "kerning", "lang", "letter_spacing", "lighting_color", "marker_end", "marker_mid", "marker_start", "mask", "opacity", "overflow", "paint_order", "pointer_events", "required_extensions", "shape_rendering", "stop_color", "stop_opacity", "stroke", "stroke_dasharray", "stroke_dashoffset", "stroke_linecap", "stroke_linejoin", "stroke_miterlimit", "stroke_opacity", "stroke_width", "style", "system_language", "tabindex", "text_anchor", "text_decoration", "text_rendering", "transform", "transform_origin", "unicode_bidi", "vector_effect", "visibility", "word_spacing", "writing_mode", "xml", "xmlns"],
    namespaces: &[],
};

pub(super) const HTML_ELEMENTS: &[Element] = &[
    Element { name: "a", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["download", "href", "hreflang", "ping", "referrerpolicy", "rel", "target", "type"], namespaces: &[] },
    Element { name: "abbr", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "address", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "area", kind: Void, globals: &GLOBAL_ATTRIBUTES, attributes: &["alt", "coords", "download", "href", "ping", "referrerpolicy", "rel", "shape", "target"], namespaces: &[] },
    Element { name: "article", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "aside", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "audio", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["autoplay", "controls", "crossorigin", "loop", "muted", "preload", "src"], namespaces: &[] },
    Element { name: "b", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "base", kind: Void, globals: &GLOBAL_ATTRIBUTES, attributes: &["href", "target"], namespaces: &[] },
    Element { name: "bdi", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "bdo", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "blockquote", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["cite"], namespaces: &[] },
    Element { name: "body", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "br", kind: Void, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "button", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["command", "commandfor", "disabled", "form", "formaction", "formenctype", "formmethod", "formnovalidate", "formtarget", "name", "popovertarget", "popovertargetaction", "type", "value"], namespaces: &[] },
    Element { name: "canvas", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["height", "width"], namespaces: &[] },
    Element { name: "caption", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "cite", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "code", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "col", kind: Void, globals: &GLOBAL_ATTRIBUTES, attributes: &["span"], namespaces: &[] },
    Element { name: "colgroup", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["span"], namespaces: &[] },
    Element { name: "data", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["value"], namespaces: &[] },
    Element { name: "datalist", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "dd", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "del", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["cite", "datetime"], namespaces: &[] },
    Element { name: "details", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["name", "open"], namespaces: &[] },
    Element { name: "dfn", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "dialog", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["open"], namespaces: &[] },
    Element { name: "div", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "dl", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "dt", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "em", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "embed", kind: Void, globals: &GLOBAL_ATTRIBUTES, attributes: &["height", "src", "type", "width"], namespaces: &[] },
    Element { name: "fieldset", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["disabled", "form", "name"], namespaces: &[] },
    Element { name: "figcaption", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "figure", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "footer", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "form", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["accept_charset", "action", "autocomplete", "enctype", "method", "name", "novalidate", "rel", "target"], namespaces: &[] },
    Element { name: "h1", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "h2", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "h3", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "h4", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "h5", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "h6", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "head", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "header", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "hgroup", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "hr", kind: Void, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "html", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "i", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "iframe", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["allow", "allowfullscreen", "height", "loading", "name", "referrerpolicy", "sandbox", "src", "srcdoc", "width"], namespaces: &[] },
    Element { name: "img", kind: Void, globals: &GLOBAL_ATTRIBUTES, attributes: &["alt", "crossorigin", "decoding", "fetchpriority", "height", "ismap", "loading", "referrerpolicy", "sizes", "src", "srcset", "usemap", "width"], namespaces: &[] },
    Element { name: "input", kind: Void, globals: &GLOBAL_ATTRIBUTES, attributes: &["accept", "alt", "autocomplete", "capture", "checked", "dirname", "disabled", "form", "formaction", "formenctype", "formmethod", "formnovalidate", "formtarget", "height", "list", "max", "maxlength", "min", "minlength", "multiple", "name", "pattern", "placeholder", "popovertarget", "popovertargetaction", "readonly", "required", "size", "src", "step", "type", "value", "width"], namespaces: &[] },
    Element { name: "ins", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["cite", "datetime"], namespaces: &[] },
    Element { name: "kbd", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "label", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["for"], namespaces: &[] },
    Element { name: "legend", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "li", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["value"], namespaces: &[] },
    Element { name: "link", kind: Void, globals: &GLOBAL_ATTRIBUTES, attributes: &["as", "blocking", "color", "crossorigin", "disabled", "fetchpriority", "href", "hreflang", "imagesizes", "imagesrcset", "integrity", "media", "referrerpolicy", "rel", "sizes", "type"], namespaces: &[] },
    Element { name: "main", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "map", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["name"], namespaces: &[] },
    Element { name: "mark", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "menu", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "meta", kind: Void, globals: &GLOBAL_ATTRIBUTES, attributes: &["charset", "content", "http_equiv", "media", "name", "property"], namespaces: &[] },
    Element { name: "meter", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["high", "low", "max", "min", "optimum", "value"], namespaces: &[] },
    Element { name: "nav", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "noscript", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "object", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["data", "form", "height", "name", "type", "width"], namespaces: &[] },
    Element { name: "ol", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["reversed", "start", "type"], namespaces: &[] },
    Element { name: "optgroup", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["disabled", "label"], namespaces: &[] },
    Element { name: "option", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["disabled", "label", "selected", "value"], namespaces: &[] },
    Element { name: "output", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["for", "form", "name"], namespaces: &[] },
    Element { name: "p", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "picture", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "pre", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "progress", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["max", "value"], namespaces: &[] },
    Element { name: "q", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["cite"], namespaces: &[] },
    Element { name: "rp", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "rt", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "ruby", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "s", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "samp", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "script", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["async", "blocking", "crossorigin", "defer", "fetchpriority", "integrity", "nomodule", "referrerpolicy", "src", "type"], namespaces: &[] },
    Element { name: "search", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "section", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "select", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["autocomplete", "disabled", "form", "multiple", "name", "required", "size"], namespaces: &[] },
    Element { name: "slot", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["name"], namespaces: &[] },
    Element { name: "small", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "source", kind: Void, globals: &GLOBAL_ATTRIBUTES, attributes: &["height", "media", "sizes", "src", "srcset", "type", "width"], namespaces: &[] },
    Element { name: "span", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "strong", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "style", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["blocking", "media"], namespaces: &[] },
    Element { name: "sub", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "summary", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "sup", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "svg", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["height", "preserveAspectRatio", "viewBox", "width", "x", "xmlns", "y"], namespaces: &[] },
    Element { name: "table", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "tbody", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "td", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["colspan", "headers", "rowspan"], namespaces: &[] },
    Element { name: "template", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["shadowrootdelegatesfocus", "shadowrootmode"], namespaces: &[] },
    Element { name: "textarea", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["autocomplete", "cols", "dirname", "disabled", "form", "maxlength", "minlength", "name", "placeholder", "readonly", "required", "rows", "wrap"], namespaces: &[] },
    Element { name: "tfoot", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "th", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["abbr", "colspan", "headers", "rowspan", "scope"], namespaces: &[] },
    Element { name: "thead", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "time", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["datetime"], namespaces: &[] },
    Element { name: "title", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "tr", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "track", kind: Void, globals: &GLOBAL_ATTRIBUTES, attributes: &["default", "kind", "label", "src", "srclang"], namespaces: &[] },
    Element { name: "u", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "ul", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "var", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "video", kind: Normal, globals: &GLOBAL_ATTRIBUTES, attributes: &["autoplay", "controls", "crossorigin", "height", "loop", "muted", "playsinline", "poster", "preload", "src", "width"], namespaces: &[] },
    Element { name: "wbr", kind: Void, globals: &GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
];

pub(super) const SVG_ELEMENTS: &[Element] = &[
    Element { name: "a", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["download", "href", "hreflang", "ping", "referrerpolicy", "rel", "target", "type"], namespaces: &[] },
    Element { name: "animate", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["accumulate", "additive", "attributeName", "begin", "by", "calcMode", "dur", "end", "fill", "from", "href", "keySplines", "keyTimes", "max", "min", "repeatCount", "repeatDur", "restart", "to", "values"], namespaces: &[] },
    Element { name: "animateMotion", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["accumulate", "additive", "begin", "by", "calcMode", "dur", "end", "fill", "from", "href", "keyPoints", "keySplines", "keyTimes", "max", "min", "origin", "path", "repeatCount", "repeatDur", "restart", "rotate", "to", "values"], namespaces: &[] },
    Element { name: "animateTransform", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["accumulate", "additive", "attributeName", "begin", "by", "calcMode", "dur", "end", "fill", "from", "href", "keySplines", "keyTimes", "max", "min", "repeatCount", "repeatDur", "restart", "to", "type", "values"], namespaces: &[] },
    Element { name: "circle", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["cx", "cy", "pathLength", "r"], namespaces: &[] },
    Element { name: "clipPath", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["clipPathUnits"], namespaces: &[] },
    Element { name: "defs", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "desc", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "ellipse", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["cx", "cy", "pathLength", "rx", "ry"], namespaces: &[] },
    Element { name: "feBlend", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["height", "in", "in2", "mode", "result", "width", "x", "y"], namespaces: &[] },
    Element { name: "feColorMatrix", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["height", "in", "result", "type", "values", "width", "x", "y"], namespaces: &[] },
    Element { name: "feComponentTransfer", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["height", "in", "result", "width", "x", "y"], namespaces: &[] },
    Element { name: "feComposite", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["height", "in", "in2", "k1", "k2", "k3", "k4", "operator", "result", "width", "x", "y"], namespaces: &[] },
    Element { name: "feConvolveMatrix", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["bias", "divisor", "edgeMode", "height", "in", "kernelMatrix", "kernelUnitLength", "order", "preserveAlpha", "result", "targetX", "targetY", "width", "x", "y"], namespaces: &[] },
    Element { name: "feDiffuseLighting", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["diffuseConstant", "height", "in", "kernelUnitLength", "result", "surfaceScale", "width", "x", "y"], namespaces: &[] },
    Element { name: "feDisplacementMap", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["height", "in", "in2", "result", "scale", "width", "x", "xChannelSelector", "y", "yChannelSelector"], namespaces: &[] },
    Element { name: "feDistantLight", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["azimuth", "elevation"], namespaces: &[] },
    Element { name: "feDropShadow", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["dx", "dy", "height", "in", "result", "stdDeviation", "width", "x", "y"], namespaces: &[] },
    Element { name: "feFlood", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["height", "result", "width", "x", "y"], namespaces: &[] },
    Element { name: "feFuncA", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["amplitude", "exponent", "intercept", "offset", "slope", "tableValues", "type"], namespaces: &[] },
    Element { name: "feFuncB", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["amplitude", "exponent", "intercept", "offset", "slope", "tableValues", "type"], namespaces: &[] },
    Element { name: "feFuncG", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["amplitude", "exponent", "intercept", "offset", "slope", "tableValues", "type"], namespaces: &[] },
    Element { name: "feFuncR", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["amplitude", "exponent", "intercept", "offset", "slope", "tableValues", "type"], namespaces: &[] },
    Element { name: "feGaussianBlur", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["edgeMode", "height", "in", "result", "stdDeviation", "width", "x", "y"], namespaces: &[] },
    Element { name: "feImage", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["crossorigin", "height", "href", "preserveAspectRatio", "result", "width", "x", "y"], namespaces: &[] },
    Element { name: "feMerge", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["height", "result", "width", "x", "y"], namespaces: &[] },
    Element { name: "feMergeNode", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["in"], namespaces: &[] },
    Element { name: "feMorphology", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["height", "in", "operator", "radius", "result", "width", "x", "y"], namespaces: &[] },
    Element { name: "feOffset", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["dx", "dy", "height", "in", "result", "width", "x", "y"], namespaces: &[] },
    Element { name: "fePointLight", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["x", "y", "z"], namespaces: &[] },
    Element { name: "feSpecularLighting", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["height", "in", "kernelUnitLength", "result", "specularConstant", "specularExponent", "surfaceScale", "width", "x", "y"], namespaces: &[] },
    Element { name: "feSpotLight", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["limitingConeAngle", "pointsAtX", "pointsAtY", "pointsAtZ", "specularExponent", "x", "y", "z"], namespaces: &[] },
    Element { name: "feTile", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["height", "in", "result", "width", "x", "y"], namespaces: &[] },
    Element { name: "feTurbulence", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["baseFrequency", "height", "numOctaves", "result", "seed", "stitchTiles", "type", "width", "x", "y"], namespaces: &[] },
    Element { name: "filter", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["filterUnits", "height", "primitiveUnits", "width", "x", "y"], namespaces: &[] },
    Element { name: "foreignObject", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["height", "width", "x", "y"], namespaces: &[] },
    Element { name: "g", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "image", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["crossorigin", "decoding", "height", "href", "preserveAspectRatio", "width", "x", "y"], namespaces: &[] },
    Element { name: "line", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["pathLength", "x1", "x2", "y1", "y2"], namespaces: &[] },
    Element { name: "linearGradient", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["gradientTransform", "gradientUnits", "href", "spreadMethod", "x1", "x2", "y1", "y2"], namespaces: &[] },
    Element { name: "marker", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["markerHeight", "markerUnits", "markerWidth", "orient", "preserveAspectRatio", "refX", "refY", "viewBox"], namespaces: &[] },
    Element { name: "mask", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["height", "maskContentUnits", "maskUnits", "width", "x", "y"], namespaces: &[] },
    Element { name: "metadata", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "mpath", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["href"], namespaces: &[] },
    Element { name: "path", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["d", "pathLength"], namespaces: &[] },
    Element { name: "pattern", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["height", "href", "patternContentUnits", "patternTransform", "patternUnits", "preserveAspectRatio", "viewBox", "width", "x", "y"], namespaces: &[] },
    Element { name: "polygon", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["pathLength", "points"], namespaces: &[] },
    Element { name: "polyline", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["pathLength", "points"], namespaces: &[] },
    Element { name: "radialGradient", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["cx", "cy", "fr", "fx", "fy", "gradientTransform", "gradientUnits", "href", "r", "spreadMethod"], namespaces: &[] },
    Element { name: "rect", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["height", "pathLength", "rx", "ry", "width", "x", "y"], namespaces: &[] },
    Element { name: "script", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["crossorigin", "href", "type"], namespaces: &[] },
    Element { name: "set", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["attributeName", "begin", "dur", "end", "fill", "href", "max", "min", "repeatCount", "repeatDur", "restart", "to"], namespaces: &[] },
    Element { name: "stop", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["offset"], namespaces: &[] },
    Element { name: "style", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["media", "title", "type"], namespaces: &[] },
    Element { name: "svg", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["height", "preserveAspectRatio", "viewBox", "width", "x", "y"], namespaces: &[] },
    Element { name: "switch", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "symbol", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["height", "preserveAspectRatio", "refX", "refY", "viewBox", "width", "x", "y"], namespaces: &[] },
    Element { name: "text", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["dx", "dy", "lengthAdjust", "rotate", "textLength", "x", "y"], namespaces: &[] },
    Element { name: "textPath", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["href", "lengthAdjust", "method", "path", "side", "spacing", "startOffset", "textLength"], namespaces: &[] },
    Element { name: "title", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &[], namespaces: &[] },
    Element { name: "tspan", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["dx", "dy", "lengthAdjust", "rotate", "textLength", "x", "y"], namespaces: &[] },
    Element { name: "use", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["height", "href", "width", "x", "y"], namespaces: &[] },
    Element { name: "view", kind: Xml, globals: &SVG_GLOBAL_ATTRIBUTES, attributes: &["preserveAspectRatio", "viewBox"], namespaces: &[] },
];

pub(super) const MODULES: &[Module] = &[
    Module { path: "aria", namespace: true, attributes: &["activedescendant", "atomic", "autocomplete", "braillelabel", "brailleroledescription", "busy", "checked", "colcount", "colindex", "colindextext", "colspan", "controls", "current", "describedby", "description", "details", "disabled", "dropeffect", "errormessage", "expanded", "flowto", "grabbed", "haspopup", "hidden", "invalid", "keyshortcuts", "label", "labelledby", "level", "live", "modal", "multiline", "multiselectable", "orientation", "owns", "placeholder", "posinset", "pressed", "readonly", "relevant", "required", "roledescription", "rowcount", "rowindex", "rowindextext", "rowspan", "selected", "setsize", "sort", "valuemax", "valuemin", "valuenow", "valuetext"], modifiers: &[] },
    Module { path: "data", namespace: true, attributes: &["attr", "bind", "class", "computed", "effect", "ignore", "ignore_morph", "indicator", "init", "json_signals", "on_intersect", "on_interval", "on_signal_patch", "on_signal_patch_filter", "preserve_attr", "ref", "show", "signals", "style", "text"], modifiers: &[] },
    Module { path: "data::modifiers", namespace: false, attributes: &[], modifiers: &[] },
    Module { path: "data::modifiers::attr", namespace: false, attributes: &[], modifiers: &[] },
    Module { path: "data::modifiers::bind", namespace: false, attributes: &[], modifiers: &["case", "event", "prop"] },
    Module { path: "data::modifiers::class", namespace: false, attributes: &[], modifiers: &["case"] },
    Module { path: "data::modifiers::computed", namespace: false, attributes: &[], modifiers: &["case"] },
    Module { path: "data::modifiers::effect", namespace: false, attributes: &[], modifiers: &[] },
    Module { path: "data::modifiers::ignore", namespace: false, attributes: &[], modifiers: &["self_"] },
    Module { path: "data::modifiers::ignore_morph", namespace: false, attributes: &[], modifiers: &[] },
    Module { path: "data::modifiers::indicator", namespace: false, attributes: &[], modifiers: &["case"] },
    Module { path: "data::modifiers::init", namespace: false, attributes: &[], modifiers: &["delay", "viewtransition"] },
    Module { path: "data::modifiers::json_signals", namespace: false, attributes: &[], modifiers: &["terse"] },
    Module { path: "data::modifiers::on", namespace: false, attributes: &[], modifiers: &["capture", "case", "debounce", "delay", "document", "once", "outside", "passive", "prevent", "stop", "throttle", "viewtransition", "window"] },
    Module { path: "data::modifiers::on_intersect", namespace: false, attributes: &[], modifiers: &["debounce", "delay", "exit", "full", "half", "once", "threshold", "throttle", "viewtransition"] },
    Module { path: "data::modifiers::on_interval", namespace: false, attributes: &[], modifiers: &["duration", "viewtransition"] },
    Module { path: "data::modifiers::on_signal_patch", namespace: false, attributes: &[], modifiers: &["debounce", "delay", "throttle"] },
    Module { path: "data::modifiers::on_signal_patch_filter", namespace: false, attributes: &[], modifiers: &[] },
    Module { path: "data::modifiers::preserve_attr", namespace: false, attributes: &[], modifiers: &[] },
    Module { path: "data::modifiers::ref", namespace: false, attributes: &[], modifiers: &["case"] },
    Module { path: "data::modifiers::show", namespace: false, attributes: &[], modifiers: &[] },
    Module { path: "data::modifiers::signals", namespace: false, attributes: &[], modifiers: &["case", "ifmissing"] },
    Module { path: "data::modifiers::style", namespace: false, attributes: &[], modifiers: &[] },
    Module { path: "data::modifiers::text", namespace: false, attributes: &[], modifiers: &[] },
    Module { path: "data::on", namespace: true, attributes: &["DOMContentLoaded", "abort", "afterprint", "animationcancel", "animationend", "animationiteration", "animationstart", "auxclick", "beforeinput", "beforeprint", "beforetoggle", "beforeunload", "blur", "cancel", "canplay", "canplaythrough", "change", "click", "close", "compositionend", "compositionstart", "compositionupdate", "contextmenu", "copy", "cut", "dblclick", "drag", "dragend", "dragenter", "dragleave", "dragover", "dragstart", "drop", "durationchange", "emptied", "ended", "error", "focus", "focusin", "focusout", "formdata", "fullscreenchange", "fullscreenerror", "gotpointercapture", "hashchange", "input", "invalid", "keydown", "keypress", "keyup", "languagechange", "load", "loadeddata", "loadedmetadata", "loadstart", "lostpointercapture", "message", "messageerror", "mousedown", "mouseenter", "mouseleave", "mousemove", "mouseout", "mouseover", "mouseup", "offline", "online", "pagehide", "pageshow", "paste", "pause", "play", "playing", "pointercancel", "pointerdown", "pointerenter", "pointerleave", "pointermove", "pointerout", "pointerover", "pointerup", "popstate", "progress", "ratechange", "readystatechange", "rejectionhandled", "reset", "resize", "scroll", "scrollend", "securitypolicyviolation", "seeked", "seeking", "select", "selectionchange", "selectstart", "slotchange", "stalled", "storage", "submit", "suspend", "timeupdate", "toggle", "touchcancel", "touchend", "touchmove", "touchstart", "transitioncancel", "transitionend", "transitionrun", "transitionstart", "unhandledrejection", "unload", "visibilitychange", "volumechange", "waiting", "wheel"], modifiers: &[] },
];
