//! Serde support for the plain structs generated by `#[derive(Cheers)]`.
//!
//! Generated impls only forward to these generic functions, so a crate type-checks one call per
//! struct instead of a full serde derive, and the serde machinery is only compiled for structs
//! that are actually (de)serialized. Behaviour matches `#[derive(Serialize, Deserialize)]` on a
//! struct with named fields and no serde attributes.

use std::{fmt, marker::PhantomData};

use serde::{
    Deserialize, Deserializer, Serialize, Serializer,
    de::{self, DeserializeSeed, IgnoredAny, MapAccess, SeqAccess, Visitor},
    ser::SerializeStruct,
};

#[doc(hidden)]
pub trait SerializeFields {
    const LEN: usize;

    fn serialize_fields<S: SerializeStruct>(
        &self,
        names: &'static [&'static str],
        state: &mut S,
    ) -> Result<(), S::Error>;
}

#[doc(hidden)]
pub trait DeserializeFields<'de>: Sized {
    const LEN: usize;
    type Slots: Default;

    fn next_from_seq<A: SeqAccess<'de>>(
        seq: &mut A,
        expecting: &dyn de::Expected,
    ) -> Result<Self, A::Error>;

    fn set_from_map<A: MapAccess<'de>>(
        slots: &mut Self::Slots,
        index: usize,
        names: &'static [&'static str],
        map: &mut A,
    ) -> Result<(), A::Error>;

    fn finish<E: de::Error>(slots: Self::Slots, names: &'static [&'static str]) -> Result<Self, E>;
}

#[doc(hidden)]
#[inline]
pub fn serialize<S: Serializer, F: SerializeFields>(
    serializer: S,
    name: &'static str,
    names: &'static [&'static str],
    fields: F,
) -> Result<S::Ok, S::Error> {
    let mut state = serializer.serialize_struct(name, F::LEN)?;
    fields.serialize_fields(names, &mut state)?;
    state.end()
}

#[doc(hidden)]
#[inline]
pub fn deserialize<'de, D: Deserializer<'de>, F: DeserializeFields<'de>>(
    deserializer: D,
    name: &'static str,
    names: &'static [&'static str],
) -> Result<F, D::Error> {
    deserializer.deserialize_struct(
        name,
        names,
        StructVisitor {
            name,
            names,
            fields: PhantomData,
        },
    )
}

struct StructVisitor<F> {
    name: &'static str,
    names: &'static [&'static str],
    fields: PhantomData<F>,
}

impl<'de, F: DeserializeFields<'de>> Visitor<'de> for StructVisitor<F> {
    type Value = F;

    fn expecting(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "struct {}", self.name)
    }

    fn visit_seq<A: SeqAccess<'de>>(self, mut seq: A) -> Result<F, A::Error> {
        let expecting = SeqExpecting {
            name: self.name,
            len: F::LEN,
        };
        F::next_from_seq(&mut seq, &expecting)
    }

    fn visit_map<A: MapAccess<'de>>(self, mut map: A) -> Result<F, A::Error> {
        let mut slots = F::Slots::default();
        while let Some(field) = map.next_key_seed(FieldSeed { names: self.names })? {
            match field {
                Some(index) => F::set_from_map(&mut slots, index, self.names, &mut map)?,
                None => {
                    map.next_value::<IgnoredAny>()?;
                }
            }
        }
        F::finish(slots, self.names)
    }
}

struct SeqExpecting {
    name: &'static str,
    len: usize,
}

impl de::Expected for SeqExpecting {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        let plural = if self.len == 1 { "" } else { "s" };
        write!(
            formatter,
            "struct {} with {} element{plural}",
            self.name, self.len
        )
    }
}

/// Resolves a map key to the index of a known field, or `None` for a field to ignore.
struct FieldSeed {
    names: &'static [&'static str],
}

impl<'de> DeserializeSeed<'de> for FieldSeed {
    type Value = Option<usize>;

    fn deserialize<D: Deserializer<'de>>(self, deserializer: D) -> Result<Self::Value, D::Error> {
        deserializer.deserialize_identifier(self)
    }
}

impl<'de> Visitor<'de> for FieldSeed {
    type Value = Option<usize>;

    fn expecting(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("field identifier")
    }

    fn visit_u64<E: de::Error>(self, index: u64) -> Result<Self::Value, E> {
        Ok(usize::try_from(index)
            .ok()
            .filter(|index| *index < self.names.len()))
    }

    fn visit_str<E: de::Error>(self, value: &str) -> Result<Self::Value, E> {
        Ok(self.names.iter().position(|name| *name == value))
    }

    fn visit_bytes<E: de::Error>(self, value: &[u8]) -> Result<Self::Value, E> {
        Ok(self.names.iter().position(|name| name.as_bytes() == value))
    }
}

/// Deserializes an absent field: `Option` fields become `None`, everything else is a
/// `missing field` error.
struct MissingField<E> {
    name: &'static str,
    error: PhantomData<E>,
}

impl<'de, E: de::Error> Deserializer<'de> for MissingField<E> {
    type Error = E;

    fn deserialize_any<V: Visitor<'de>>(self, _visitor: V) -> Result<V::Value, E> {
        Err(E::missing_field(self.name))
    }

    fn deserialize_option<V: Visitor<'de>>(self, visitor: V) -> Result<V::Value, E> {
        visitor.visit_none()
    }

    serde::forward_to_deserialize_any! {
        bool i8 i16 i32 i64 i128 u8 u16 u32 u64 u128 f32 f64 char str string
        bytes byte_buf unit unit_struct newtype_struct seq tuple
        tuple_struct map struct enum identifier ignored_any
    }
}

fn missing_field<'de, T: Deserialize<'de>, E: de::Error>(name: &'static str) -> Result<T, E> {
    T::deserialize(MissingField {
        name,
        error: PhantomData,
    })
}

macro_rules! impl_fields {
    ($len:literal => $($ty:ident $index:tt),+) => {
        impl<$($ty: Serialize),+> SerializeFields for ($(&$ty,)+) {
            const LEN: usize = $len;

            #[inline]
            fn serialize_fields<S: SerializeStruct>(
                &self,
                names: &'static [&'static str],
                state: &mut S,
            ) -> Result<(), S::Error> {
                $(state.serialize_field(names[$index], self.$index)?;)+
                Ok(())
            }
        }

        impl<'de, $($ty: Deserialize<'de>),+> DeserializeFields<'de> for ($($ty,)+) {
            const LEN: usize = $len;
            type Slots = ($(Option<$ty>,)+);

            fn next_from_seq<A: SeqAccess<'de>>(
                seq: &mut A,
                expecting: &dyn de::Expected,
            ) -> Result<Self, A::Error> {
                Ok(($(
                    match seq.next_element()? {
                        Some(value) => value,
                        None => return Err(de::Error::invalid_length($index, expecting)),
                    },
                )+))
            }

            fn set_from_map<A: MapAccess<'de>>(
                slots: &mut Self::Slots,
                index: usize,
                names: &'static [&'static str],
                map: &mut A,
            ) -> Result<(), A::Error> {
                match index {
                    $($index => {
                        if slots.$index.is_some() {
                            return Err(de::Error::duplicate_field(names[$index]));
                        }
                        slots.$index = Some(map.next_value()?);
                    })+
                    _ => unreachable!("field index comes from `names`"),
                }
                Ok(())
            }

            fn finish<E: de::Error>(
                slots: Self::Slots,
                names: &'static [&'static str],
            ) -> Result<Self, E> {
                Ok(($(
                    match slots.$index {
                        Some(value) => value,
                        None => missing_field(names[$index])?,
                    },
                )+))
            }
        }
    };
}

impl_fields!(1 => T0 0);
impl_fields!(2 => T0 0, T1 1);
impl_fields!(3 => T0 0, T1 1, T2 2);
impl_fields!(4 => T0 0, T1 1, T2 2, T3 3);
impl_fields!(5 => T0 0, T1 1, T2 2, T3 3, T4 4);
impl_fields!(6 => T0 0, T1 1, T2 2, T3 3, T4 4, T5 5);
impl_fields!(7 => T0 0, T1 1, T2 2, T3 3, T4 4, T5 5, T6 6);
impl_fields!(8 => T0 0, T1 1, T2 2, T3 3, T4 4, T5 5, T6 6, T7 7);
impl_fields!(9 => T0 0, T1 1, T2 2, T3 3, T4 4, T5 5, T6 6, T7 7, T8 8);
impl_fields!(10 => T0 0, T1 1, T2 2, T3 3, T4 4, T5 5, T6 6, T7 7, T8 8, T9 9);
impl_fields!(11 => T0 0, T1 1, T2 2, T3 3, T4 4, T5 5, T6 6, T7 7, T8 8, T9 9, T10 10);
impl_fields!(12 => T0 0, T1 1, T2 2, T3 3, T4 4, T5 5, T6 6, T7 7, T8 8, T9 9, T10 10, T11 11);

#[cfg(test)]
mod tests {
    use serde::{Deserialize, Deserializer, Serialize, Serializer};

    #[derive(Debug, PartialEq, Serialize, Deserialize)]
    struct Derived {
        open: bool,
        title: String,
        note: Option<String>,
    }

    #[derive(Debug, PartialEq)]
    struct Forwarded {
        open: bool,
        title: String,
        note: Option<String>,
    }

    const NAMES: &[&str] = &["open", "title", "note"];

    impl Serialize for Forwarded {
        fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
            super::serialize(
                serializer,
                "Derived",
                NAMES,
                (&self.open, &self.title, &self.note),
            )
        }
    }

    impl<'de> Deserialize<'de> for Forwarded {
        fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
            let (open, title, note) = super::deserialize::<D, (bool, String, Option<String>)>(
                deserializer,
                "Derived",
                NAMES,
            )?;
            Ok(Self { open, title, note })
        }
    }

    fn forwarded(derived: &Derived) -> Forwarded {
        Forwarded {
            open: derived.open,
            title: derived.title.clone(),
            note: derived.note.clone(),
        }
    }

    #[test]
    fn serializes_like_serde_derive() {
        for derived in [
            Derived {
                open: true,
                title: "a".into(),
                note: Some("b".into()),
            },
            Derived {
                open: false,
                title: String::new(),
                note: None,
            },
        ] {
            assert_eq!(
                serde_json::to_string(&forwarded(&derived))
                    .expect("forwarded impl should serialize"),
                serde_json::to_string(&derived).expect("derived impl should serialize"),
            );
        }
    }

    #[test]
    fn deserializes_like_serde_derive() {
        for json in [
            r#"{"open":true,"title":"a","note":"b"}"#,
            r#"{"title":"a","open":false}"#,
            r#"{"open":true,"title":"a","note":null,"unknown":[1,{"x":2}]}"#,
            r#"[true,"a","b"]"#,
            r#"[true,"a",null]"#,
            r#"{"open":true}"#,
            r#"{"open":true,"open":false,"title":"a"}"#,
            r#"{"open":1,"title":"a"}"#,
            r#"[true]"#,
            r#"[true,"a","b",4]"#,
            r#""open""#,
        ] {
            let derived = serde_json::from_str::<Derived>(json).map_err(|error| error.to_string());
            let forwarded = serde_json::from_str::<Forwarded>(json)
                .map(|forwarded| Derived {
                    open: forwarded.open,
                    title: forwarded.title,
                    note: forwarded.note,
                })
                .map_err(|error| error.to_string());
            assert_eq!(forwarded, derived, "{json}");
        }
    }
}
