use std::cell::{Cell, RefCell};

use crate::{
    context::AttributeValue,
    render::{AttributeBuffer, Render, Rendered},
};

#[doc(hidden)]
/// Stream type used by generated async render code.
///
/// This is an implementation detail of the `html!` macro and is not part of
/// Cheers' stable public API.
pub type AsyncStream = ::std::pin::Pin<Box<dyn futures::Stream<Item = Rendered<String>> + Send>>;

#[doc(hidden)]
/// Streaming key of an `@async` block with its markers precomputed by the
/// `html!` macro.
///
/// This is an implementation detail of the `html!` macro and is not part of
/// Cheers' stable public API.
pub struct StaticAsyncKey {
    pub key: &'static str,
    pub template_start: &'static str,
    pub script: &'static str,
    pub island_open: &'static str,
}

#[doc(hidden)]
/// Streaming key of one rendered instance of an `@async` block.
///
/// Keys only contain URL-safe base64, `.`, `-` and digits, so they are written
/// without escaping.
///
/// This is an implementation detail of the `html!` macro and is not part of
/// Cheers' stable public API.
pub enum AsyncKey {
    Static(&'static StaticAsyncKey),
    Dynamic(Box<str>),
}

impl AsyncKey {
    #[doc(hidden)]
    #[inline]
    #[must_use]
    pub fn as_str(&self) -> &str {
        match self {
            Self::Static(key) => key.key,
            Self::Dynamic(key) => key,
        }
    }

    #[doc(hidden)]
    #[inline]
    pub fn write_template_start(&self, out: &mut String) {
        match self {
            Self::Static(key) => out.push_str(key.template_start),
            Self::Dynamic(key) => {
                out.push_str("<template data-ssr=\"");
                out.push_str(key);
                out.push_str("-t\">");
            }
        }
    }

    #[doc(hidden)]
    #[inline]
    pub fn write_script(&self, out: &mut String) {
        match self {
            Self::Static(key) => out.push_str(key.script),
            Self::Dynamic(key) => {
                out.push_str("</template><script data-ssr=\"");
                out.push_str(key);
                out.push_str("-s\">__ssrStream('");
                out.push_str(key);
                out.push_str("')</script>");
            }
        }
    }

    #[doc(hidden)]
    #[inline]
    pub fn write_island_open(&self, out: &mut String) {
        match self {
            Self::Static(key) => out.push_str(key.island_open),
            Self::Dynamic(key) => {
                out.push_str("<div data-cheers-async-root=\"");
                out.push_str(key);
                out.push_str("\" data-ssr=\"");
                out.push_str(key);
                out.push_str("\">");
            }
        }
    }
}

impl Render<AttributeValue> for AsyncKey {
    #[inline]
    fn render_to(&self, buffer: &mut AttributeBuffer) {
        // XSS SAFETY: keys are generated by Cheers and never need escaping
        buffer.dangerously_get_string().push_str(self.as_str());
    }
}

#[doc(hidden)]
/// Streams started while rendering one async scope: the page itself, or the
/// body of an `@async` block that contains nested `@async` blocks.
///
/// This is an implementation detail of the `html!` macro and is not part of
/// Cheers' stable public API.
pub struct AsyncScope {
    streams: RefCell<Vec<AsyncStream>>,
    key_prefix: Option<Box<str>>,
}

impl AsyncScope {
    #[doc(hidden)]
    #[inline]
    #[must_use]
    pub const fn root() -> Self {
        Self {
            streams: RefCell::new(Vec::new()),
            key_prefix: None,
        }
    }

    #[doc(hidden)]
    /// Scope for the body of the `@async` block keyed `parent`.
    ///
    /// Blocks nested in a repeated parent get the parent's key as a prefix,
    /// which keeps their keys distinct between parent instances.
    #[inline]
    #[must_use]
    pub fn nested(parent: &AsyncKey) -> Self {
        Self {
            streams: RefCell::new(Vec::new()),
            key_prefix: match parent {
                AsyncKey::Static(_) => None,
                AsyncKey::Dynamic(key) => Some(key.clone()),
            },
        }
    }

    #[doc(hidden)]
    /// Returns the key of the `instance`-th rendered instance of a block.
    ///
    /// The first instance in an unprefixed scope keeps the static key, so
    /// single-instance blocks have the same key on every render.
    #[must_use]
    pub fn key(&self, key: &'static StaticAsyncKey, instance: u32) -> AsyncKey {
        if instance == 0 && self.key_prefix.is_none() {
            return AsyncKey::Static(key);
        }

        let mut instance_buffer = itoa::Buffer::new();
        let instance = (instance > 0).then(|| instance_buffer.format(instance));
        let prefix = self.key_prefix.as_deref();

        let mut dynamic = String::with_capacity(
            prefix.map_or(0, |prefix| prefix.len() + 1)
                + key.key.len()
                + instance.map_or(0, |instance| instance.len() + 1),
        );
        if let Some(prefix) = prefix {
            dynamic.push_str(prefix);
            dynamic.push('.');
        }
        dynamic.push_str(key.key);
        if let Some(instance) = instance {
            dynamic.push('-');
            dynamic.push_str(instance);
        }

        AsyncKey::Dynamic(dynamic.into_boxed_str())
    }

    #[doc(hidden)]
    #[inline]
    pub fn push(&self, stream: AsyncStream) {
        self.streams.borrow_mut().push(stream);
    }

    #[doc(hidden)]
    #[inline]
    pub fn activate<F: FnOnce(AsyncKey) -> AsyncStream>(&self, slot: &AsyncSlot<F>, key: AsyncKey) {
        let Some(stream) = slot.stream.take() else {
            debug_assert!(
                false,
                "an `@async` block was rendered more than once from a single prebuilt stream, \
                 likely by a component that renders its children more than once; only the first \
                 copy of its fallback is replaced"
            );
            return;
        };

        self.push(stream(key));
    }

    #[doc(hidden)]
    #[inline]
    #[must_use]
    pub fn into_streams(self) -> Vec<AsyncStream> {
        self.streams.into_inner()
    }
}

#[doc(hidden)]
/// An `@async` stream built ahead of rendering, started only when its block
/// is rendered.
///
/// This is an implementation detail of the `html!` macro and is not part of
/// Cheers' stable public API.
pub struct AsyncSlot<F> {
    stream: Cell<Option<F>>,
}

impl<F: FnOnce(AsyncKey) -> AsyncStream> AsyncSlot<F> {
    #[doc(hidden)]
    #[inline]
    pub const fn new(stream: F) -> Self {
        Self {
            stream: Cell::new(Some(stream)),
        }
    }
}

#[doc(hidden)]
/// Counts the rendered instances of an `@async` block built in place.
///
/// This is an implementation detail of the `html!` macro and is not part of
/// Cheers' stable public API.
pub struct AsyncInstances(Cell<u32>);

impl AsyncInstances {
    #[doc(hidden)]
    #[inline]
    #[must_use]
    pub const fn new() -> Self {
        Self(Cell::new(0))
    }

    #[doc(hidden)]
    #[inline]
    #[must_use]
    pub fn next(&self) -> u32 {
        let instance = self.0.get();
        self.0.set(instance + 1);
        instance
    }
}

#[cfg(test)]
mod tests {
    use super::{AsyncKey, AsyncScope, StaticAsyncKey};

    const KEY: StaticAsyncKey = StaticAsyncKey {
        key: "Ab3_xQ",
        template_start: "<template data-ssr=\"Ab3_xQ-t\">",
        script: "</template><script data-ssr=\"Ab3_xQ-s\">__ssrStream('Ab3_xQ')</script>",
        island_open: "<div data-cheers-async-root=\"Ab3_xQ\" data-ssr=\"Ab3_xQ\">",
    };

    fn markers(key: &AsyncKey) -> [String; 3] {
        let mut template_start = String::new();
        let mut script = String::new();
        let mut island_open = String::new();
        key.write_template_start(&mut template_start);
        key.write_script(&mut script);
        key.write_island_open(&mut island_open);
        [template_start, script, island_open]
    }

    #[test]
    fn dynamic_markers_match_static_markers() {
        let static_key = AsyncScope::root().key(&KEY, 0);
        let dynamic_key = AsyncKey::Dynamic(KEY.key.into());

        assert!(matches!(static_key, AsyncKey::Static(_)));
        assert_eq!(markers(&static_key), markers(&dynamic_key));
    }

    #[test]
    fn repeated_and_nested_instances_get_distinct_keys() {
        let root = AsyncScope::root();
        let second = root.key(&KEY, 1);
        assert_eq!(second.as_str(), "Ab3_xQ-1");

        let nested = AsyncScope::nested(&second);
        assert_eq!(nested.key(&KEY, 0).as_str(), "Ab3_xQ-1.Ab3_xQ");
        assert_eq!(nested.key(&KEY, 2).as_str(), "Ab3_xQ-1.Ab3_xQ-2");

        let under_static = AsyncScope::nested(&root.key(&KEY, 0));
        assert!(matches!(under_static.key(&KEY, 0), AsyncKey::Static(_)));
    }
}
