use std::{
    fmt::{Debug, Display},
    marker::PhantomData,
};

use serde::Deserialize;

use crate::{
    context::AttributeValue,
    render::{Buffer, Render},
};

/// A DOM id generated for a component.
///
/// `ElementId` is not meant to be constructed manually.
///
/// - Inside the component that defines the ids, acquire `ElementId` values with
///   [`ids!`](crate::prelude::ids).
/// - Outside that component, acquire them through the generated associated functions such as
///   `YourComponent::id(...)` and `YourComponent::id_name(...)`.
///
/// `ElementId` is used heavily when targeting patches at specific DOM nodes. It also renders as
/// an attribute value, so it can still be reused for attributes such as `id`, `for`, and
/// `aria-labelledby` when needed.
///
/// # Example
///
/// ```
/// use cheers::prelude::*;
///
/// #[derive(Cheers)]
/// struct Row {
///     #[id]
///     id: u32,
/// }
///
/// impl Render for Row {
///     fn render_to(&self, buffer: &mut Buffer<Element>) {
///         ids!(id);
///
///         html! {
///             tr id=id {}
///         }
///         .render_to(buffer);
///     }
/// }
///
/// assert_eq!(
///     Row { id: 4 }.render().into_inner(),
///     r#"<tr id="row-4"></tr>"#,
/// );
///
/// assert_eq!(Row::id(4).to_string(), "row-4");
/// ```
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
#[repr(transparent)]
pub struct ElementId(pub(crate) String);

impl<'de> Deserialize<'de> for ElementId {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        Ok(ElementId(s))
    }
}

impl Display for ElementId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        std::fmt::Display::fmt(&self.0, f)
    }
}

impl AsRef<ElementId> for ElementId {
    fn as_ref(&self) -> &ElementId {
        self
    }
}

impl ElementId {
    #[doc(hidden)]
    /// Used by the code generated by `#[derive(Cheers)]` for `#[id(...)]` fields and
    /// by the `ids!` helper macro. Not part of the stable public API.
    pub fn __dynamic(s: String) -> Self {
        Self(s)
    }
}

impl Render<AttributeValue> for ElementId {
    fn render_to(&self, buffer: &mut Buffer<AttributeValue>) {
        self.0.render_to(buffer);
    }
}

#[derive(Debug)]
enum InnerSignalPath {
    Static(&'static str),
    Dynamic(String),
}

/// A typed reference to a client-side signal.
///
/// `Signal<T>` is not meant to be constructed manually.
///
/// - Inside the component that defines the signal, acquire it with
///   [`signals!`](crate::prelude::signals).
/// - For component-local state defined inside a component, acquire it with
///   [`scoped_signal!`](crate::scoped_signal).
/// - Outside the component that defines the signal, acquire it through the generated associated
///   functions such as `YourComponent::signal_name(...)`.
///
/// When rendered in an attribute position, a signal becomes a `$`-prefixed path understood by the
/// client-side runtime.
///
/// # Example
///
/// ```
/// use cheers::prelude::*;
///
/// #[derive(Cheers)]
/// struct Counter {
///     #[signal]
///     count: i32,
/// }
///
/// impl Render for Counter {
///     fn render_to(&self, buffer: &mut Buffer<Element>) {
///         signals!(signal_count);
///
///         html! {
///             span !text(signal_count) {}
///         }
///         .render_to(buffer);
///     }
/// }
///
/// assert_eq!(
///     Counter { count: 3 }.render().into_inner(),
///     r#"<span data-text="$counter.count"></span>"#,
/// );
///
/// let count: Signal<i32> = Counter::signal_count();
/// assert_eq!(
///     html! { span !text(count) {} }.render().into_inner(),
///     r#"<span data-text="$counter.count"></span>"#,
/// );
/// ```
#[derive(Debug)]
pub struct Signal<T> {
    path: InnerSignalPath,
    ty: PhantomData<T>,
}

/// Creates a component-local signal whose name is scoped to the current call site.
///
/// Use this when defining local state inside a component, not when referencing a component signal
/// from outside. Scoped signals are intentionally internal to the component that creates them.
///
/// The generated signal path includes a hash derived from the source location, so it is not a
/// stable external name that other components or callers should target directly. To reference a
/// signal from outside its component, use that component's generated `signal_...` associated
/// functions instead.
///
/// This is useful for component-local UI state such as loading spinners.
///
/// # Example
///
/// ```
/// use cheers::prelude::*;
///
/// let fetching: Signal<bool> = scoped_signal!("spinner.fetching");
/// let rendered = html! {
///     button !on:click("@get('/items')") !indicator(fetching) { "Refresh" }
///     div !show(fetching) { "Loading..." }
/// }
/// .render()
/// .into_inner();
///
/// assert!(rendered.contains("data-indicator=\"spinner.fetching"));
/// assert!(rendered.contains("data-show=\"$spinner.fetching"));
/// ```
#[macro_export]
macro_rules! scoped_signal {
    ($name:literal $(, $id:expr)*) => {{
        let mut name = ::std::string::String::from($name);
        $(
            name.push('.');
            name.push_str(&$id.to_string());
        )*
        ::cheers::prelude::Signal::__scoped(name, ::std::file!(), ::std::line!(), ::std::column!())
    }};
}

impl<T> Signal<T> {
    #[doc(hidden)]
    /// Used by the code generated by `#[derive(Cheers)]` when generating signal
    /// accessors for components without an id field. Not part of the stable public API.
    pub const fn __static(path: &'static str) -> Self {
        Self {
            path: InnerSignalPath::Static(path),
            ty: PhantomData::<T>,
        }
    }

    #[doc(hidden)]
    /// Used by the `scoped_signal!` macro. Not part of the stable public API.
    pub fn __scoped(mut name: String, file: &'static str, line: u32, column: u32) -> Self {
        let hash = hash_location(file, line, column);
        name.push_str(&hash.to_string());

        Self {
            path: InnerSignalPath::Dynamic(name),
            ty: PhantomData::<T>,
        }
    }

    #[doc(hidden)]
    /// Used by the code generated by `#[derive(Cheers)]` when generating signal
    /// accessors for components with an id field. Not part of the stable public API.
    pub fn __string(path: String) -> Self {
        Signal {
            path: InnerSignalPath::Dynamic(path),
            ty: PhantomData::<T>,
        }
    }

    #[doc(hidden)]
    /// Used internally by the macro support methods on [`Signal`]. Not part of the stable
    /// public API.
    pub fn __path(&self) -> &str {
        match &self.path {
            InnerSignalPath::Static(path) => path,
            InnerSignalPath::Dynamic(path) => path.as_str(),
        }
    }

    #[doc(hidden)]
    /// Used by the `html!`, `html_borrow!`, `attribute!`, and `attribute_borrow!`
    /// macros when expanding computed signal attributes. Not part of the stable public API.
    pub fn __computed_open(&self, buffer: &mut Buffer<AttributeValue>) -> usize {
        let path = self.__path();
        let segments: Vec<&str> = path.split('.').collect();

        if segments.is_empty() {
            return 0;
        }

        for (i, segment) in segments.iter().enumerate() {
            if i == 0 {
                segment.render_to(buffer);
            } else {
                // XSS SAFETY: statically opening the JS object
                buffer.dangerously_get_string().push_str(":{");
                segment.render_to(buffer);
            }
        }
        // XSS SAFETY: statically assigning a JS function - the execution is intentional
        buffer.dangerously_get_string().push_str(":()=>");

        segments.len() - 1
    }
}

impl Signal<()> {
    #[doc(hidden)]
    /// Used by the `html!`, `html_borrow!`, `attribute!`, and `attribute_borrow!`
    /// macros when expanding computed signal attributes. Not part of the stable public API.
    pub fn __computed_close(count: usize, buffer: &mut Buffer<AttributeValue>) {
        // XSS SAFETY: statically closing the JS object
        let buf = buffer.dangerously_get_string();
        for _ in 0..count {
            buf.push('}');
        }
    }
}

impl<T: Render<AttributeValue>> Signal<T> {
    #[doc(hidden)]
    /// Used by the `html!`, `html_borrow!`, `attribute!`, and `attribute_borrow!`
    /// macros when expanding `!signals(...)`. Not part of the stable public API.
    pub fn __assign(&self, buffer: &mut Buffer<AttributeValue>, v: T) {
        let path = self.__path();
        let segments: Vec<&str> = path.split('.').collect();

        if segments.is_empty() {
            return;
        }

        {
            let mut first = true;
            for seg in segments.iter() {
                if first {
                    first = false;
                    seg.render_to(buffer);
                } else {
                    // XSS SAFETY: statically opening the JS object
                    buffer.dangerously_get_string().push_str(":{");
                    seg.render_to(buffer);
                }
            }
            // XSS SAFETY: static assignment
            buffer.dangerously_get_string().push(':');
        }

        v.render_to(buffer);

        // XSS SAFETY: statically closing the JS object
        let s = buffer.dangerously_get_string();
        for _ in 0..segments.len() - 1 {
            s.push('}');
        }
    }
}

impl<T> Render<AttributeValue> for Signal<T> {
    fn render_to(&self, buffer: &mut Buffer<AttributeValue>) {
        '$'.render_to(buffer);
        self.__path().render_to(buffer);
    }
}

/// A form field name generated for a component.
///
/// `FormName` is only meant to be acquired with [`form_names!`](crate::prelude::form_names)
/// inside the component that defines the form fields.
///
/// Form names are component-local and are not meant to be referenced from outside the component.
/// They render as attribute values and are used for `name=` on form controls.
///
/// # Example
///
/// ```
/// use cheers::prelude::*;
///
/// #[derive(Cheers)]
/// struct LoginForm {
///     #[form]
///     email: String,
/// }
///
/// impl Render for LoginForm {
///     fn render_to(&self, buffer: &mut Buffer<Element>) {
///         form_names!(form_email);
///
///         html! {
///             input name=(form_email);
///         }
///         .render_to(buffer);
///     }
/// }
///
/// assert_eq!(
///     LoginForm {
///         email: String::from("hello@example.com"),
///     }
///     .render()
///     .into_inner(),
///     r#"<input name="email">"#,
/// );
/// ```
#[derive(Debug, Clone, Copy)]
pub struct FormName(&'static str);

impl FormName {
    #[doc(hidden)]
    /// Used by the code generated by `#[derive(Cheers)]` and exposed through the
    /// `form_names!` macro. Not part of the stable public API.
    pub const fn __static(s: &'static str) -> Self {
        Self(s)
    }
}

impl Render<AttributeValue> for FormName {
    fn render_to(&self, buffer: &mut Buffer<AttributeValue>) {
        self.0.render_to(buffer);
    }
}

/// Computes 32-bit FNV1a hash from a location
pub(crate) const fn hash_location(file: &'static str, line: u32, column: u32) -> u32 {
    const FNV_OFFSET_BASIS_32: u32 = 0x811c9dc5;
    const FNV_PRIME_32: u32 = 0x01000193;

    let bytes = file.as_bytes();
    let mut hash = FNV_OFFSET_BASIS_32;
    let mut i = 0;

    while i < bytes.len() {
        hash ^= bytes[i] as u32;
        hash = hash.wrapping_mul(FNV_PRIME_32);
        i += 1;
    }

    let line_bytes = line.to_ne_bytes();
    i = 0;
    while i < 4 {
        hash ^= line_bytes[i] as u32;
        hash = hash.wrapping_mul(FNV_PRIME_32);
        i += 1;
    }

    let column_bytes = column.to_ne_bytes();
    i = 0;
    while i < 4 {
        hash ^= column_bytes[i] as u32;
        hash = hash.wrapping_mul(FNV_PRIME_32);
        i += 1;
    }

    hash
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn signal_object_string_value() {
        let signal = Signal::<&str>::__string("user.name".to_string());
        let mut buffer = Buffer::new();
        signal.__assign(&mut buffer, "'Nick'");
        assert_eq!(buffer.rendered().into_inner(), r#"user:{name:'Nick'}"#);
    }

    #[test]
    fn signal_object_number_value() {
        let signal = Signal::<f64>::__string("user.age".to_string());
        let mut buffer = Buffer::new();
        signal.__assign(&mut buffer, -42.0);
        assert_eq!(buffer.rendered().into_inner(), r#"user:{age:-42.0}"#);
    }

    #[test]
    fn hash_different_locations() {
        const HASH1: u32 = hash_location("src/main.rs", 10, 5);
        const HASH2: u32 = hash_location("src/main.rs", 10, 6);

        assert_ne!(HASH1, HASH2);
    }

    #[test]
    fn hash_same_locations() {
        const HASH1: u32 = hash_location("src/main.rs", 42, 13);
        const HASH2: u32 = hash_location("src/main.rs", 42, 13);

        assert_eq!(HASH1, HASH2);
    }
}
