use std::convert::Infallible;

use futures::StreamExt;

use crate::{
    async_stream::AsyncScope,
    context::Context,
    render::{Buffer, Lazy, Render, Rendered},
};

/// A page rendered by `html!` from a template containing `@async` blocks.
///
/// The response streams the page with each block's fallback first, then each block's content as
/// it loads.
pub struct AsyncLazy<F: AsyncRender> {
    render: F,
}

mod sealed {
    pub trait Sealed {}
}

/// The render body of an [`AsyncLazy`], as generated by `html!`.
pub trait AsyncRender: sealed::Sealed {
    #[doc(hidden)]
    fn render_async(&self, buffer: &mut Buffer, scope: &AsyncScope);
}

impl<F: Fn(&mut Buffer, &AsyncScope)> sealed::Sealed for F {}

impl<F: Fn(&mut Buffer, &AsyncScope)> AsyncRender for F {
    #[inline]
    fn render_async(&self, buffer: &mut Buffer, scope: &AsyncScope) {
        self(buffer, scope);
    }
}

impl<F: Fn(&mut Buffer, &AsyncScope)> AsyncLazy<F> {
    #[doc(hidden)]
    /// Used by the `html!` macro for templates containing `@async` blocks.
    /// Not part of the stable public API.
    pub const fn __new(render: F) -> Self {
        Self { render }
    }
}

impl<F: AsyncRender> axum::response::IntoResponse for AsyncLazy<F> {
    fn into_response(self) -> axum::response::Response {
        let mut buffer = Buffer::new();
        let scope = AsyncScope::root();
        self.render.render_async(&mut buffer, &scope);
        let streams = scope.into_streams();
        let immediate = buffer.rendered().into_inner();

        let body = axum::body::Body::from_stream(
            futures::stream::once(async { Ok(immediate) }).chain(
                futures::stream::select_all(streams)
                    .map(|s| s.into_inner())
                    .map(Ok::<_, Infallible>),
            ),
        );

        (
            [
                ("Content-Type", "text/html; charset=UTF-8"),
                ("X-Content-Type-Options", "nosniff"),
                ("Cache-Control", "no-transform"),
                ("Transfer-Encoding", "chunked"),
            ],
            body,
        )
            .into_response()
    }
}

impl<F: Fn(&mut Buffer<C>), C: Context> axum::response::IntoResponse for Lazy<F, C>
where
    Lazy<F, C>: Render,
{
    fn into_response(self) -> axum::response::Response {
        self.render().into_response()
    }
}

impl axum::response::IntoResponse for Rendered<String> {
    fn into_response(self) -> axum::response::Response {
        (
            [("Content-Type", "text/html; charset=UTF-8")],
            self.into_inner(),
        )
            .into_response()
    }
}
